apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

#namespace: marcielns

images:
- name: goserver
  newName: marcielramos/gitopsfc
  newTag: newtag